Generate player votes database, containing votes for Serie A matchday and player.

Votes data is manually downloaded from https://www.fantacalcio.it/voti-fantacalcio-serie-a

Serie A calendar is loaded from another file, to add information not containing in votes files: home/away, team opponent.

In [1]:
import pandas as pd
import numpy as np

In [2]:
cal = np.array(pd.read_excel('fantacalcio/seriea_calendar.xlsx', header = None))

cal_df = pd.DataFrame(columns = ['matchday', 'team1', 'team2'])

matchday = 0

for i in range(cal.shape[0]):
    if(cal[i, 0][0].isnumeric()):
        matchday = matchday + 1
        continue
    
    teams = cal[i, 0].split('-')
    
    frame = pd.DataFrame([[matchday, teams[0], teams[1]]], columns = cal_df.columns)

    cal_df = pd.concat([cal_df, frame], ignore_index = True)

In [3]:
cal_df

    matchday       team1        team2
0          1  Fiorentina    Cremonese
1          1      Verona       Napoli
2          1    Juventus     Sassuolo
3          1       Lazio      Bologna
4          1       Lecce        Inter
..       ...         ...          ...
375       38       Milan        Lazio
376       38    Sassuolo        Monza
377       38      Napoli  Salernitana
378       38     Udinese    Sampdoria
379       38        Roma       Spezia

[380 rows x 3 columns]

In [ ]:
df = pd.DataFrame(columns = ['matchday', 'player', 'team', 'oppteam', 'home', 'vote', 'goals', 'assists', 'cards_malus', 'fantavote'])

LAST_MATCH = 38

for matchday in range(1, LAST_MATCH + 1):
    
    votes_file = 'fantacalcio/voti/Voti_Fantacalcio_Stagione_2022_23_Giornata_' + str(matchday) + '.xlsx'



    try:
        rx = np.array(pd.read_excel(votes_file, header = None))
    except:
        print('Last matchday: ' + str(matchday-1))
        break

    read = 0
    for i in range(rx.shape[0]):
        if(rx[i, 0] == "Cod."):
            read = 1
            team = rx[i-1, 0];
            continue

        if(read):
            if(isinstance(rx[i, 0], int)):
                if((isinstance(rx[i, 3], float) or isinstance(rx[i, 3], int)) and rx[i, 1] != "ALL") :
                    player = rx[i, 2];
                    vote = float(rx[i, 3])
                    goals = rx[i, 4] + rx[i, 8] - rx[i, 5]
                    assists = rx[i, 12]
                    cards_malus = rx[i, 10] * 0.5 + rx[i, 11]
                    
                    oppteam = ''
                    home = 0
                    for j in range(cal_df.shape[0]):
                        if(cal_df['matchday'][j] == matchday):
                            if(cal_df['team1'][j] == team):
                                oppteam = cal_df['team2'][j] 
                                home = 1
                            elif(cal_df['team2'][j] == team):
                                oppteam = cal_df['team1'][j] 
                                home = 0

                    goals_gen = goals * 3;
                    if(goals < 0):
                        goals_gen = goals
                        
                    fantavote = vote + goals_gen + assists - cards_malus 
                    
                    frame = pd.DataFrame([[matchday, player, team, oppteam, home, vote, goals, assists, cards_malus, fantavote]], columns = df.columns)

                    df = pd.concat([df, frame], axis = 0, ignore_index = True)
            else:
                read = 0
                continue

    df

In [5]:
df

,matchday,player,team,oppteam,home,vote,goals,assists,cards_malus,fantavote
0,1,Musso,Atalanta,Sampdoria,0,6.0,0,0,0.5,5.5
1,1,Toloi,Atalanta,Sampdoria,0,7.0,1,0,0.0,10.0
2,1,Djimsiti,Atalanta,Sampdoria,0,6.0,0,0,0.0,6.0
3,1,Hateboer,Atalanta,Sampdoria,0,6.0,0,0,0.5,5.5
4,1,Okoli,Atalanta,Sampdoria,0,5.5,0,0,0.5,5.0
...,...,...,...,...,...,...,...,...,...,...
4010,14,Sulemana I.,Verona,Juventus,1,6.0,0,0,0.0,6.0
4011,14,Lasagna,Verona,Juventus,1,6.0,0,0,0.0,6.0
4012,14,Kallon,Verona,Juventus,1,5.5,0,0,0.0,5.5
4013,14,Djuric,Verona,Juventus,1,6.0,0,0,0.5,5.5
4014,14,Henry,Verona,Juventus,1,6.5,0,0,0.0,6.5

In [6]:
df.to_excel('mid_outputs/players_votes.xlsx')

Elaborate data for past seasons.

Do not repeat if data is already present.

In [7]:
cal_df = pd.read_excel('fantacalcio/season2122/seriea_calendar.xlsx')

to_drop = list()

for i in range(cal_df.shape[0]):
    if(not isinstance(cal_df['matchday'][i], int)):
        to_drop.append(i)
    
cal_df = cal_df.drop(to_drop)

cal_df = cal_df.reset_index(drop = True)

cal_df

    matchday        team1        team2
0          1       Verona     Sassuolo
1          1        Inter        Genoa
2          1       Empoli        Lazio
3          1       Torino     Atalanta
4          1      Bologna  Salernitana
..       ...          ...          ...
375       38       Spezia       Napoli
376       38     Sassuolo        Milan
377       38        Inter    Sampdoria
378       38  Salernitana      Udinese
379       38      Venezia     Cagliari

[380 rows x 3 columns]

In [8]:
df = pd.DataFrame(columns = ['matchday', 'player', 'team', 'oppteam', 'home', 'vote', 'goals', 'assists', 'cards_malus', 'fantavote'])

LAST_MATCH = 38

for matchday in range(1, LAST_MATCH + 1):
    
    votes_file = 'fantacalcio/season2122/voti/Voti_Fantacalcio_Stagione_2021_22_Giornata_' + str(matchday) + '.xlsx'




    rx = np.array(pd.read_excel(votes_file, header = None))

    read = 0
    for i in range(rx.shape[0]):
        if(rx[i, 0] == "Cod."):
            read = 1
            team = rx[i-1, 0];
            continue

        if(read):
            if(isinstance(rx[i, 0], int)):
                if((isinstance(rx[i, 3], float) or isinstance(rx[i, 3], int)) and rx[i, 1] != "ALL") :
                    player = rx[i, 2];
                    vote = float(rx[i, 3])
                    goals = rx[i, 4] + rx[i, 8] - rx[i, 5]
                    assists = rx[i, 12]
                    cards_malus = rx[i, 10] * 0.5 + rx[i, 11]
                    
                    oppteam = ''
                    home = 0
                    for j in range(cal_df.shape[0]):
                        if(cal_df['matchday'][j] == matchday):
                            if(cal_df['team1'][j] == team):
                                oppteam = cal_df['team2'][j] 
                                home = 1
                            elif(cal_df['team2'][j] == team):
                                oppteam = cal_df['team1'][j] 
                                home = 0

                    goals_gen = goals * 3;
                    if(goals < 0):
                        goals_gen = goals
                        
                    fantavote = vote + goals_gen + assists - cards_malus 
                    
                    frame = pd.DataFrame([[matchday, player, team, oppteam, home, vote, goals, assists, cards_malus, fantavote]], columns = df.columns)

                    df = pd.concat([df, frame], axis = 0, ignore_index = True)
            else:
                read = 0
                continue

    df

In [9]:
df.to_excel('mid_outputs/season2122/players_votes.xlsx')

In [10]:
cal_df = pd.read_excel('fantacalcio/season2021/seriea_calendar.xlsx')

to_drop = list()

for i in range(cal_df.shape[0]):
    if(not isinstance(cal_df['matchday'][i], int)):
        to_drop.append(i)
    
cal_df = cal_df.drop(to_drop)

cal_df = cal_df.reset_index(drop = True)

cal_df

    matchday       team1      team2
0          1  Fiorentina     Torino
1          1      Verona       Roma
2          1       Parma     Napoli
3          1       Genoa    Crotone
4          1    Sassuolo   Cagliari
..       ...         ...        ...
375       38    Sassuolo      Lazio
376       38    Atalanta      Milan
377       38      Torino  Benevento
378       38     Bologna   Juventus
379       38      Napoli     Verona

[380 rows x 3 columns]

In [11]:
df = pd.DataFrame(columns = ['matchday', 'player', 'team', 'oppteam', 'home', 'vote', 'goals', 'assists', 'cards_malus', 'fantavote'])

LAST_MATCH = 38

for matchday in range(1, LAST_MATCH + 1):
    
    votes_file = 'fantacalcio/season2021/voti/Voti_Fantacalcio_Stagione_2020_21_Giornata_' + str(matchday) + '.xlsx'




    rx = np.array(pd.read_excel(votes_file, header = None))

    read = 0
    for i in range(rx.shape[0]):
        if(rx[i, 0] == "Cod."):
            read = 1
            team = rx[i-1, 0];
            continue

        if(read):
            if(isinstance(rx[i, 0], int)):
                if((isinstance(rx[i, 3], float) or isinstance(rx[i, 3], int)) and rx[i, 1] != "ALL") :
                    player = rx[i, 2];
                    vote = float(rx[i, 3])
                    goals = rx[i, 4] + rx[i, 8] - rx[i, 5]
                    assists = rx[i, 12]
                    cards_malus = rx[i, 10] * 0.5 + rx[i, 11]
                    
                    oppteam = ''
                    home = 0
                    for j in range(cal_df.shape[0]):
                        if(cal_df['matchday'][j] == matchday):
                            if(cal_df['team1'][j] == team):
                                oppteam = cal_df['team2'][j] 
                                home = 1
                            elif(cal_df['team2'][j] == team):
                                oppteam = cal_df['team1'][j] 
                                home = 0

                    goals_gen = goals * 3;
                    if(goals < 0):
                        goals_gen = goals
                        
                    fantavote = vote + goals_gen + assists - cards_malus 
                    
                    frame = pd.DataFrame([[matchday, player, team, oppteam, home, vote, goals, assists, cards_malus, fantavote]], columns = df.columns)

                    df = pd.concat([df, frame], axis = 0, ignore_index = True)
            else:
                read = 0
                continue

    df

In [12]:
df.to_excel('mid_outputs/season2021/players_votes.xlsx')